# Generated by Django 2.2.4 on 2019-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_sale', models.PositiveIntegerField()),
                ('day_id', models.PositiveSmallIntegerField()),
                ('month_id', models.PositiveSmallIntegerField()),
                ('year_id', models.PositiveSmallIntegerField()),
                ('product', models.ManyToManyField(related_name='orders', to='product.Product')),
            ],
            options={
                'verbose_name_plural': 'sales',
                'db_table': 'sale_data',
            },
        ),
    ]
