# Generated by Django 2.2.4 on 2019-08-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
