# Generated by Django 2.2.4 on 2019-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
